# Generated by Django 4.1.3 on 2022-11-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='uploaderID',
            new_name='uploader',
        ),
    ]
