# Generated by Django 4.1.3 on 2022-11-15 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0002_rename_uploaderid_video_uploader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='vidID',
            new_name='video',
        ),
    ]
